### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by Daeseong-Yu** [ehharvey/lms-2024#193]
![image](https://github.com/user-attachments/assets/6e97276d-cc21-4040-9b8f-87648a6350c0)

I have a problem cloning the repository.

error: invalid path 'wiki/announcements/What should our first steps be?.md'

Is it only for me?

**Comment by ehharvey** [comment]
Oh hmm I see.

I'm wondering if my path names don't work on windows...

I'll see if I can push a change in a second!

**Comment by ehharvey** [comment]
I can't fix this now but I will when I get home tonight!

Basically I need to adjust the files in wiki/announcements/ so that they don't have a question mark.

If you feel comfortable doing that via the GitHub web ui go for it! Otherwise will be good tomorrow :)

**Comment by ehharvey** [comment]
@Daeseong-Yu you should be good to go now :) but lmk if this is still an issue
