### ISSUE TITLE
Change Credits module to Credit (singular)

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/lms-2024#212]
Our modules should be singular

**Comment by chauhan2b** [comment]
Can you elaborate the issue?

private String EhharveyCredits() {...} BECOMES private String EhharveyCredit() {...} ?

**Comment by ehharvey** [comment]
Hi! Apologies, did not see this.

All of our modules (e.g., classes) should be singular. So the class itself should be `Credit`, not `Credits`. This should also affect the command use (instead of `lms credits list` it should be `lms credit list`).

As for members inside the Credits module, I'm less concerned, but could be worth changing too.

I would like focus on the module / command though.
